## Author:  Katie Hanss
## Class:   Senior Thesis
## Description: This file contains methods that help 
## manipulate activities.

## ------------------------------------------------------------ ##
## input:    an fitparse_activity generated by fitparse
## outputs:  a dictionary where keys are fields ('distance', 
##           'timestamp' etc.) and values are a list 
## ------------------------------------------------------------ ##
def get_dict_of_fields(fitparse_activity):

    ## get unique fields in the fitparse_activity
    fields = {field for record in fitparse_activity.get_records_as_dicts('record') for field in record.keys()}

    ## make a dictionary of fields
    activity_dict = dict()
    for field in fields:
        activity_dict[field] = []

    ## fill in dictionary with appropriate fields
    for record in fitparse_activity.get_records_as_dicts('record'):
        for field in fields:

            ## if field in this record append
            if field in record:
                activity_dict[field].append(record[field])

            ## else append None
            else:
                activity_dict[field].append(None)

    return activity_dict