# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timestamp',
        ),
    ]
