# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 01:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to=b'')),
                ('name', models.CharField(default='Run', max_length=100, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_records', models.PositiveIntegerField(default=None, null=True)),
                ('tot_dist', models.FloatField(null=True)),
                ('avg_speed', models.FloatField(null=True)),
                ('avg_hr', models.PositiveIntegerField(null=True)),
                ('avg_cadence', models.PositiveIntegerField(null=True)),
                ('timestamp', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(null=True), default=None, null=True, size=None)),
                ('position_lat', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=None, null=True, size=None)),
                ('position_long', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=None, null=True, size=None)),
                ('distance', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), default=None, null=True, size=None)),
                ('altitude', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), default=None, null=True, size=None)),
                ('speed', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), default=None, null=True, size=None)),
                ('heart_rate', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), default=None, null=True, size=None)),
                ('cadence', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), default=None, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('run_id', models.PositiveIntegerField()),
                ('timedelta', models.FloatField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('position_lat', models.IntegerField(null=True)),
                ('position_long', models.IntegerField(null=True)),
                ('distance', models.FloatField(null=True)),
                ('altitude', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('heart_rate', models.PositiveIntegerField(null=True)),
                ('cadence', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
