# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_delete_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='elevation_gained',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
