# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athletes', '0005_activity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.FloatField(default=None)),
                ('count', models.PositiveIntegerField(default=0, null=True)),
                ('total_distance', models.FloatField(default=0, null=True)),
                ('avg_avg_speed', models.FloatField(default=0, null=True)),
                ('avg_max_speed', models.FloatField(default=0, null=True)),
                ('avg_avg_hr', models.PositiveIntegerField(default=0, null=True)),
                ('avg_max_hr', models.PositiveIntegerField(default=0, null=True)),
                ('avg_avg_cadence', models.PositiveIntegerField(default=0, null=True)),
                ('avg_max_cadence', models.PositiveIntegerField(default=0, null=True)),
                ('avg_elevation_gained', models.PositiveIntegerField(default=0, null=True)),
                ('total_elevation_gained', models.PositiveIntegerField(default=0, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='max_cadence',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_hr',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_speed',
            field=models.FloatField(null=True),
        ),
    ]
