# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_auto_20170202_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='week',
            field=models.FloatField(default=None),
        ),
    ]
