# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_activity_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='week',
            field=models.FloatField(default=None, null=True),
        ),
    ]
