# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 18:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athletes', '0008_auto_20170202_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='week',
            name='user',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
