# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0015_remove_activity_session_rpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tot_minutes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
