# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0016_activity_tot_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='tot_minutes',
        ),
    ]
