# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0018_activity_tot_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='week',
        ),
    ]
