# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0021_auto_20170304_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
