# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0022_tag_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeks',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'get_latest_by': 'start_time'},
        ),
        migrations.DeleteModel(
            name='Weeks',
        ),
    ]
