# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0024_remove_activity_avg_speed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.TextField(default=None, null=True),
        ),
    ]
