# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0026_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='allow_access',
            field=models.BooleanField(default=True),
        ),
    ]
