# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0028_activity_met_expectation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='met_expectation',
        ),
    ]
