# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 13:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0030_activity_met_expectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='rpe',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(null=True), default=None, null=True, size=None),
        ),
    ]
